#!/bin/bash
# Script para aplicar configuración de red mirrored en WSL
# Ejecutar desde PowerShell en Windows

echo "=== Configuración de Red Mirrored para WSL ==="
echo ""
echo "Archivo .wslconfig creado en: C:\Users\artur\.wslconfig"
echo "Contenido:"
echo "  [wsl2]"
echo "  networkingMode=mirrored"
echo ""
echo "PASOS PARA APLICAR LOS CAMBIOS:"
echo ""
echo "1. Cerrar Docker Desktop completamente"
echo "2. Abrir PowerShell como Administrador en Windows"
echo "3. Ejecutar: wsl --shutdown"
echo "4. Esperar 10-15 segundos"
echo "5. Abrir Docker Desktop nuevamente"
echo "6. Abrir una nueva terminal WSL"
echo ""
echo "VERIFICACIÓN:"
echo "Desde el contenedor Docker, probar:"
echo "  docker exec -it <container_name> ping 192.168.11.22"
echo "  docker exec -it <container_name> curl http://192.168.11.22"
echo ""
echo "Si funciona, el contenedor ahora tendrá acceso a ambas redes!"
echo "========================================"